name: test_wf
on: 
  push:
    branches:
      - master
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name : steps for testing
        run: echo welcome to nice
      - name : step 2
        run: 
            echo from step 2
            pwd
            ll
      - run: echo from step 3
