name: test_wf
on: 
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
  
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: steps for testing
        run: echo welcome to nice
      - name: step 2
        run: |
          echo "from step 2"
          pwd
          uname -a
      - run: echo from step 3
