name: test_wf
on: 
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
  
jobs:
  test-job-1:
    runs-on: self-hosted
    steps:
      - name: steps for testing
        run: |
          echo welcome to nice
          sleep 10
      - name: step 2
        run: |
          echo "from step 2"
          pwd
          uname -a
          sleep 10
      - run: |
          echo from step 3
          sleep 10

  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: steps for testing
        run: |
          echo welcome to nice
          sleep 10
      - name: step 2
        run: |
          echo "from step 2"
          pwd
          uname -a
          sleep 10
      - run: |
          echo from step 3
          sleep 10
